backend:
  name: git-gateway
  branch: master 

publish_mode: editorial_workflow
media_folder: static/img/uploads
public_folder: img/uploads

collections:
  - label: Pages
    name: pages
    files:
      - label: Landing Page
        name: landing-page
        file: content/index.md
        fields: 
          - label: Header
            name: header
            widget: object
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Image, name: img, widget: image}
          - label: Mid Section
            name: mid-section
            widget: list
            fields: 
              - label: Description
                name: description
                widget: object
                fields: 
                  - {label: Title, name: title, widget: string}
                  - {label: Slug, name: slug, widget: string}
                  - {label: Text, name: text, widget: text}
                  - {label: Image, name: img, widget: image}
          - {label: Form Title, name: form-title, widget: string}
          